### ISSUE TITLE
Have a version for Firefox too

### ISSUE THREAD

**Issue by erkinalp** [xenova/commentblock#1]

**Comment by xenova** [comment]
On the TODO list! :)

**Comment by xenova** [comment]
There we go! :) https://addons.mozilla.org/en-US/firefox/addon/ytcommentblock/

Just remember to change to "Always allow on YouTube.com", since the extension is loaded and runs while you browse.
![image](https://user-images.githubusercontent.com/26504141/220106559-88458779-a02d-4e9b-838a-862f0489555a.png)

---

Also, I'm not sure if YouTube is A/B testing, but they are experimenting with user *handles* for commenter names (instead of names). In some sense, it's both a good thing and a bad thing: Good because scammers usually advertise in their name (and it is a lot harder to do with ascii characters (vs. emojis, strange characters and so on), but also a bad thing since it makes detection a more difficult in some cases (since only the text can be used in the detection algorithms). Do you also see this change, or is it just me (because on Chrome, I see the names (not handles)?

Either way, the extension still works when blocking link spam and other things, for example:

- Before:
![image](https://user-images.githubusercontent.com/26504141/220108392-4c3606aa-3dce-45c4-9654-97b3e268228f.png)

- After:
![image](https://user-images.githubusercontent.com/26504141/220108415-8f79de89-cde7-4d3a-9f0b-bece027c9d51.png)

**Comment by KendallDoesCoding** [comment]
@xenova @erkinalp - Please close this issue!
